schema_term_tracker = {
    "type": "object",
    "description": "PPSC AoU Core Metadata piece to track and provide basic information about terms used in the AoU study.",
    "title": "PPSC AoU Term Tracker",
    "version": "0.0.1",
    "properties": {
        "schemaVersion": {
            "title": "Schema version",
            "description": "Version of the overall schema (for each entry/row in the tracker) used at time of annotation; auto-populated equal to the value of the version key for the overall schema; should be constant for all rows in tracker.",
            "type": "string",
            "priority": "schema, auto"
        },
        "termId": {
            "title": "Term ID",
            "description": "ID assigned to each term; prefix is 'term-' followed by a number starting with 1 for the first term, and iterating by 1 for each successive term (i.e. term-1, term-2, etc.)",
            "type": "string",
            "pattern": "^term-+-*[0-9]*[1-9][0-9]*$",
            "priority": "all, high, auto"
        },
        "termTitle": {
            "title": "Term Title",
            "description": "Human readable name of the term, and the generally accepted way this term is used in the AoU Program - e.g. Registered participant, Core participant, etc.",
            "type": "string",
            "priority": "all, high"
        },
        "termName": {
            "title": "Term Name",
            "description": "Human AND machine readable version of Term Title - In order to make Term Name both human and machine readable, 1) name must start with a lower case letter, 2) name must end with a lower case letter or number, 3) only characters allowed are lower case letters, numbers, and hyphens (use hyphen instead of space), 4) name has a max length of 50, 5) name must be unique (append an iterable number as a suffix to make unique if necessary; e.g. \"-1\", \"-2\")",
            "type": "string",
            "pattern": "^(?=.{3,50}$)[a-z]+(-*)([a-z0-9]+)(-[a-z,0-9]+)*$",
            "priority": "all, high"
        },
        "termType": {
            "title" : "Term Type",
            "description": "Program concept or area to which the term is related.",
            "type": "string",
            "enum": ["","enrollment","program-milestones","eligibility","ehr","researcher-workbench","retention"],
            "priority": "all, high"
        },
        "termDescription": {
            "title": "Term Description",
            "description": "Provide a brief description of the term.",
            "type": "string",
            "priority": "all, high"
        },
        "termUseCase": {
            "title": "Term Use Case",
            "description": "Provide a brief description of use case(s) for the term.",
            "type": "array",
            "items": {
                "type": "string"
            },
            "priority": "all, high"
        },
        "annotationCreateDateTime": {
            "title": "Tracker entry creation datetime",
            "description": "Date time at which the annotation file was created; auto-inferred",
            "type": "string",
            "priority": "tracker, auto"
        },
        "annotationModDateTime": {
            "title": "Tracker entry modification datetime",
            "description": "Date time at which the annotation file was last modified; auto-inferred",
            "type": "string",
            "priority": "tracker, auto"
        },
        "termIdNumber": {
            "title": "Term ID Number",
            "description": "Numeric part of the ID; autogenerated from ID; used for easy sorting by ID file", 
            "type": "integer",
            #"pattern": "^resource-+-*[0-9]*[1-9][0-9]*$",
            "priority": "tracker, auto"
        },
        "annotationModTimeStamp": {
            "title": "Tracker entry modification datetime timestamp",
            "description": "Date time at which the annotation was last modified, converted to timestamp for easy sorting by datetime; auto-inferred",
            "type": "number",
            "priority": "tracker, auto"
        },
        "removed": {
            "title": "Removed status",
            "description": "True if term removed/deprecated.",
            "type": "integer",
            "enum": [0,1],
            "priority": "tracker, auto"
        }
    }
}