name: Bundle CLI for Windows

on:
  push:
    tags:
      - "*"
jobs:
  release:
    name: Create a release from a tag
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Download artifacts (the zipped pyinstaller exe for each os)
        uses: actions/download-artifact@v3
      - name: Release with bundles
        uses: softprops/action-gh-release@v1
        with:
          draft: true
  bundle:
    name: Bundle cli for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    needs: release
    strategy:
      matrix:
        include:
          - os: windows-latest
            name: windows
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Bundle CLI
      run: |
        pyinstaller --icon=heal-icon.ico --add-data="heal-icon.ico;." --collect-all pipe --hidden-import pipe --hidden-import pyreadstat._readstat_writer --hidden-import pyreadstat.worker --paths=. --debug=all dsc_pkg_tool.py
    - name: Zip exe (for windows) 
      run: |
        python -m zipfile -c dsc-pkg-tool-${{ matrix.name }}.zip dist/dsc_pkg_tool.exe 
    - name: Release with bundles
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        files: |
          *dsc-pkg-tool-${{ matrix.name }}.zip