name: Bundle EXE 

on:
  push:
    tags:
      - "*"
jobs:
  release:
    name: Create a release from a tag
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Download artifacts (the zipped pyinstaller exe for each os)
        uses: actions/download-artifact@v3
      - name: Release with bundles
        uses: softprops/action-gh-release@v1
        with:
          draft: true
  bundle:
    name: Bundle exe for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    needs: release
    strategy:
      matrix:
        include:
          - os: windows-latest
            name: windows
          - os: macos-latest
            name: mac
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    # add git tag version to app script
    # NOTE: ${GITHUB_REF//./-} is bash syntax for referencing the default environment $GITHUB_REF and replacing dots with dashes (in the form //<tobereplaced>/<replacewith>)
    # NOTE: ${{ matrix.name }} is for referencing github workflow variables (and is not bash syntax)

    - name: Add version number to app script
      run: |
        title="DSC Data Packaging Tool - alpha"
        title_with_version = "DSC Data Packaging Tool - alpha - ${GITHUBREF//./-}"
        sed -i -e "s/${title}/${title_with_version}/g" dsc_pkg_tool.py 
    - name: Bundle EXE for mac  
      run: |
        pyinstaller --icon=heal-icon.ico --add-data="heal-icon.ico:." --collect-all pipe --hidden-import pipe --hidden-import pyreadstat._readstat_writer --hidden-import pyreadstat.worker --paths=. --debug=all --onefile dsc_pkg_tool.py
      if: ${{ matrix.name == 'mac' }} 
    - name: Bundle EXE for windows 
      run: |
        pyinstaller --icon=heal-icon.ico --add-data="heal-icon.ico;." --collect-all pipe --hidden-import pipe --hidden-import pyreadstat._readstat_writer --hidden-import pyreadstat.worker --paths=. --debug=all --onefile dsc_pkg_tool.py
      if: ${{matrix.name == 'windows' }} 
    - name: Zip exe (for windows) and no ext (for ubuntu/mac)
      run: |
        zipped_file_name=dsc-pkg-tool-${{ matrix.name }}${GITHUB_REF//./-}.zip
        python -m zipfile -c  $zipped_file_name dist/dsc_pkg_tool.exe dist/dsc_pkg_tool
    - name: Release with bundles
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        files: |
          *dsc-pkg-tool-${{ matrix.name }}${GITHUB_REF//./-}.zip